// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.0.2")]
[assembly: AssemblyInformationalVersionAttribute("0.0.2-alpha")]
[assembly: AssemblyCompanyAttribute("Heartysoft Solutions Limited")]
[assembly: AssemblyCopyrightAttribute("Copyright © Heartysoft Solutions Limited 2015")]
[assembly: AssemblyMetadataAttribute("githash","master-e8218a")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.2";
    }
}
